#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-llaves
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-llaves"

ERROR() {
	echo -e "\e[1;31m${1}\e[0m"
}

ADVERTENCIA() {
	echo -e "\e[1;33m${1}\e[0m"
}

EXITO() {
	echo -e "\e[1;32m${1}\e[0m"
}

case ${1} in

	configure)
		ACTIVE="$( ls -1 /usr/share/keyrings/* | grep "CANAIMA-ACTIVE-" )"
		DEPRECATED="$( ls -1 /usr/share/keyrings/* | grep "CANAIMA-DEPRECATED-" )"

		ADVERTENCIA "Añadiendo llaves del repositorio oficial de Canaima"
		for KEY in ${ACTIVE}; do
			KEYID="$( echo ${KEY} | sed 's|/usr/share/keyrings/CANAIMA-ACTIVE-||g;s|.gpg||g' )"
			if [ $( apt-key list | grep -c "${KEYID}" ) -eq 0 ]; then
				echo "Añadiendo llave '${KEYID}'"
				apt-key add ${KEY} 1>/dev/null 2>&1
			fi
		done

		ADVERTENCIA "Removiendo llaves obsoletas del repositorio oficial de Canaima"
		for KEY in ${DEPRECATED}; do
			KEYID="$( echo ${KEY} | sed 's|/usr/share/keyrings/CANAIMA-DEPRECATED-||g;s|.gpg||g' )"
			if [ $( apt-key list | grep -c "${KEYID}" ) -ge 1 ]; then
				echo "Removiendo llave '${KEYID}'"
				apt-key del ${KEYID} 1>/dev/null 2>&1
			fi
		done
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
