#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-llaves
# ARCHIVO: prerm
# DESCRIPCIÓN: Prepara el sistema para que el paquete sea removido.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-llaves"

ERROR() {
	echo -e "\e[1;31m${1}\e[0m"
}

ADVERTENCIA() {
	echo -e "\e[1;33m${1}\e[0m"
}

EXITO() {
	echo -e "\e[1;32m${1}\e[0m"
}

case ${1} in

	remove|upgrade|deconfigure)
		ACTIVE="$( ls -1 /usr/share/keyrings/ | grep "CANAIMA-ACTIVE-" )"

		ADVERTENCIA "Removiendo llaves del repositorio oficial de Canaima"
		for KEY in ${ACTIVE}; do
			KEYID="$( echo ${KEY} | sed 's|/usr/share/keyrings/CANAIMA-ACTIVE-||g;s|.gpg||g' )"
			if [ $( apt-key list | grep -c "${KEYID}" ) -ge 1 ]; then
				echo "Removiendo llave '${KEYID}'"
				apt-key del ${KEYID} 1>/dev/null 2>&1
			fi
		done
	;;

	failed-upgrade)
	;;

	*)

		echo "prerm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
